# Generated by Django 5.1.7 on 2025-03-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("room", "name")},
        ),
    ]
