# Generated by Django 5.1.7 on 2025-03-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_participant_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairing",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
